/* eslint-disable @typescript-eslint/no-explicit-any */

// Phase 9C: Manifest Generator
// This module is responsible for generating the Execution Manifest based on the Portfolio Blueprint.
// It translates the high-level blueprint decisions into a detailed, actionable manifest
// that Phase 10 can use for project generation.

import type { PortfolioBlueprint } from "../blueprint/types"; // Assuming Blueprint types are defined
import type { ExecutionManifest } from "../generation/execution-manifest.types"; // Phase 10 input type

/**
 * Generates the Execution Manifest from a given Portfolio Blueprint.
 * This function acts as the orchestrator for Phase 9C.
 *
 * @param {PortfolioBlueprint} blueprint - The Portfolio Blueprint generated by Phase 9B.
 * @returns {Promise<ExecutionManifest>} The generated Execution Manifest.
 * @throws {Error} If the blueprint is invalid or manifest generation fails.
 */
export async function generateProjectManifest(blueprint: PortfolioBlueprint): Promise<ExecutionManifest> {
  console.log("--> Phase 9C: Generating Project Manifest...");

  // Basic validation for the blueprint
  if (!blueprint || !blueprint.framework || !blueprint.language) {
    throw new Error("Invalid Portfolio Blueprint: Missing essential information (framework, language).");
  }

  // --- Core Manifest Generation Logic ---
  // This section translates blueprint decisions into the structured Execution Manifest.
  // It includes deriving configurations, dependencies, structures, etc.

  const manifest: ExecutionManifest = {
    // Step 1: Project Initialization
    projectInitialization: {
      framework: blueprint.framework,
      language: blueprint.language,
      projectRoot: "generated-project", // Default root, can be customized
      packageManager: blueprint.language === "typescript" ? "npm" : "npm", // Default to npm, adjust if needed
      environmentVariables: { NODE_ENV: "development" }, // Default env vars
      projectMetadata: {
        name: "ai-generated-portfolio", // Default name, could be influenced by blueprint intent
        version: "0.1.0",
        description: "AI-generated portfolio project based on blueprint",
      },
    },

    // Step 2: Dependency Engine
    dependencies: {
      frameworkDependencies: getFrameworkDependencies(blueprint.framework, blueprint.language),
      uiLibraries: getUiLibraries(blueprint.libraries?.ui, blueprint.framework),
      animationLibraries: blueprint.animations?.library ? [blueprint.animations.library] : [],
      iconLibraries: ["lucide-react"], // Default icon library
      chartLibraries: [], // Default, can be added based on blueprint needs
      utilities: ["axios"], // Common utility
      devDependencies: ["typescript", "eslint", "prettier"], // Default dev dependencies
      peerDependencies: ["react"], // Common peer dependency
      optionalDependencies: [],
      dependencyVersionCompatibility: { "react": "^18.2.0" }, // Example version compatibility
    },

    // Step 3: Project Structure Engine
    projectStructure: {
      folders: blueprint.folderStrategy || ["src/components", "src/layouts", "src/sections", "public"], // Use blueprint or default
    },

    // Step 4: Configuration Engine
    configuration: {
      frameworkConfig: getFrameworkConfig(blueprint.framework),
        tsConfig: getTsConfig(blueprint.language),
      eslintConfig: getEslintConfig(),
      prettierConfig: getPrettierConfig(),
      buildScripts: getBuildScripts(blueprint.framework),
      tailwindConfig: getTailwindConfig(blueprint.theme?.colors),
      postcssConfig: getPostcssConfig(),
      aliases: { "@": "src" }, // Default alias
    },

    // Step 5: Theme Engine
    theme: getThemeTokens(blueprint.theme),

    // Step 6: Provider Engine
    providers: {
      required: getRequiredProviders(blueprint.libraries?.ui, blueprint.framework, blueprint.language),
    },

    // Step 7: Routing Engine
    routing: {
      routes: getRoutes(blueprint.sections, blueprint.navigation?.structure),
      navigationStructure: blueprint.navigation?.structure,
    },

    // Step 8: Component Generation Engine
    components: getComponentDefinitions(blueprint.components, blueprint.sections, blueprint.layout?.sectionHierarchy),

    // Step 9: Layout Engine
    layout: getLayoutDefinition(blueprint.layout),

    // Step 10: Animation Engine
    animations: getAnimationConfig(blueprint.animations),

    // Step 11: Content Engine
    content: getPlaceholderContent(blueprint.sections, blueprint.content),

    // Step 12: SEO Engine
    seo: getSeoConfig(blueprint.seo),

    // Step 13: Accessibility Engine
    accessibility: getAccessibilityConfig(blueprint.accessibility),

    // Step 14: Performance Engine
    performance: getPerformanceConfig(blueprint.performance),
  };

  console.log("<-- Phase 9C: Project Manifest Generation Complete.");
  return manifest;
}

// --- Helper functions to derive manifest details from blueprint ---

function getFrameworkDependencies(framework: string, language: string): string[] {
  const deps = [];
  switch (framework) {
    case "nextjs":
      deps.push("next", "react", "react-dom");
      break;
    case "react":
      deps.push("react", "react-dom");
      break;
    // Add cases for other frameworks (vue, angular, svelte, etc.)
    default:
      deps.push("react", "react-dom"); // Default to React if not specified
  }
  if (language === "typescript") {
    // Add relevant TS types if not already included by framework deps
    if (!deps.includes("@types/react")) deps.push("@types/react");
  }
  return deps;
}

function getUiLibraries(uiLib?: string, framework?: string): string[] {
  const libs: string[] = [];
  if (uiLib) {
    libs.push(uiLib);
    // Add related dependencies like tailwindcss if uiLib is tailwind based
    if (uiLib === "tailwindcss" || uiLib.includes("tailwind")) {
      if (!libs.includes("tailwindcss")) libs.push("tailwindcss");
    }
  } else if (framework === "nextjs" || framework === "react") {
    // Default UI lib for common frameworks if none specified
    if (!libs.includes("tailwindcss")) libs.push("tailwindcss");
  }
  return libs;
}

function getFrameworkConfig(framework: string): any {
  // Return framework-specific config objects
  switch (framework) {
    case "nextjs":
      return { nextConfig: { experimental: { appDir: true } } }; // Example Next.js config
    case "react":
      return null; // React itself doesn't have a central config file like Next.js
    // Add cases for other frameworks
    default:
      return null;
  }
}

function getTsConfig(language: string): any {
  if (language !== "typescript") return null;
  return {
    compilerOptions: {
      target: "ES2016",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      forceConsistentCasingInFileNames: true,
      noEmit: true,
      module: "esnext",
      moduleResolution: "node",
      resolveJsonModule: true,
      isolatedModules: true,
      esModuleInterop: true,
      // Add React specific options if framework is React-based
      jsx: "preserve", // or "react-jsx"
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"], // Adjust includes based on framework structure
    exclude: ["node_modules"],
  };
}

function getEslintConfig(): any {
  return {
    extends: ["next/core-web-vitals", "plugin:react/recommended", "plugin:@typescript-eslint/recommended"], // Example config
    parser: "@typescript-eslint/parser",
    plugins: ["react", "@typescript-eslint"],
    rules: {
      // Custom rules
    },
  };
}

function getPrettierConfig(): any {
  return {
    semi: true,
    trailingComma: "all",
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    // Add other Prettier rules
  };
}

function getBuildScripts(framework: string): BuildScripts {
  switch (framework) {
    case "nextjs":
      return { dev: "next dev", build: "next build", start: "next start" };
    case "react":
      // Assuming a setup like Vite or Create React App
      return { dev: "npm run dev", build: "npm run build", start: "npm run preview" };
    // Add cases for other frameworks
    default:
      return { dev: "npm run dev", build: "npm run build", start: "npm run start" };
  }
}

function getTailwindConfig(colors?: Record<string, string>): any {
  const themeColors = colors || {
    primary: "#0070f3",
    secondary: "#141414",
    accent: "#f5a623",
  };
  return {
    content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
    theme: {
      extend: {
        colors: themeColors,
        // Add other Tailwind extensions like spacing, typography etc.
      },
    },
    plugins: [],
  };
}

function getPostcssConfig(): any {
  // Default PostCSS config, often minimal when using Tailwind CLI or Next.js build
  return {
    plugins: {
      "tailwindcss/nesting": {},
      tailwindcss: {},
      autoprefixer: {},
    },
  };
}

function getThemeTokens(themeBlueprint?: any): ThemeTokens {
  // Default theme tokens, merge with blueprint theme data
  return {
    colors: themeBlueprint?.colors || {
      primary: "#0070f3",
      secondary: "#141414",
      accent: "#f5a623",
      background: "#ffffff",
      text: "#141414",
    },
    typography: themeBlueprint?.typography || {
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
      fontSize: { base: "16px" },
    },
    spacing: themeBlueprint?.spacing || {
      "1": "0.25rem", "2": "0.5rem", "3": "0.75rem", "4": "1rem",
    },
    radius: themeBlueprint?.radius || { "DEFAULT": "0.5rem", "lg": "1rem" },
    shadows: themeBlueprint?.shadows || {
      "DEFAULT": "0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px 0 rgba(0,0,0,0.06)",
      "md": "0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)",
    },
    themeMode: themeBlueprint?.themeMode || "system",
  };
}

function getRequiredProviders(uiLib?: string, framework?: string, language?: string): string[] {
  const providers: string[] = [];
  providers.push("ThemeProvider"); // Assumed common provider
  if (language === "typescript") {
    providers.push("TypeProvider"); // Example for TS
  }
  if (uiLib && uiLib.includes("shadcn")) {
    providers.push("ShadcnProvider"); // Example if shadcn is used
  }
  // Add other providers based on detected libraries or framework needs
  // E.g., AnimationProvider if animation library is specified
  return providers;
}

function getRoutes(sections: any[] = [], navStructure?: string[]): Route[] {
  const routes: Route[] = [];
  // Default home route
  routes.push({ path: "/", componentName: "HomePage", metadata: { title: "Home" } });

  // Generate routes based on blueprint sections or navigation structure
  const sectionNames = sections.map(s => s.name.charAt(0).toUpperCase() + s.name.slice(1));
  const structure = navStructure || sectionNames;

  structure.forEach(item => {
    const path = `/${item.toLowerCase().replace(/\s+/g, '-')}`; // Simple path generation
    if (!routes.some(route => route.path === path)) {
      routes.push({
        path: path,
        componentName: `${item}Page`, // Assuming page components match section names
        metadata: { title: item },
      });
    }
  });

  return routes;
}

function getComponentDefinitions(componentsBlueprint?: any[], sections?: any[], sectionHierarchy?: string[]): ComponentDefinition[] {
  const componentDefs: ComponentDefinition[] = [];

  // Add default components like Navbar, Footer if not explicitly defined
  componentDefs.push({ name: "Navbar", variant: "minimal", theme: {}, layout: {}, animation: {}, accessibility: {}, responsiveRules: {} });
  componentDefs.push({ name: "Footer", variant: "minimal", theme: {}, layout: {}, animation: {}, accessibility: {}, responsiveRules: {} });

  // Add components based on blueprint components list
  if (componentsBlueprint) {
    componentsBlueprint.forEach(comp => {
      componentDefs.push({
        name: comp.name,
        variant: comp.variant || "default",
        theme: comp.theme || {},
        layout: comp.layout || {},
        animation: comp.animation || {},
        accessibility: comp.accessibility || {},
        responsiveRules: comp.responsiveRules || {},
        props: comp.props,
        contentKey: comp.contentKey,
      });
    });
  }

  // Ensure components exist for sections defined in the blueprint
  const sectionNames = sections?.map(s => s.name) || [];
  const hierarchy = sectionHierarchy || sectionNames;

  hierarchy.forEach(sectionName => {
    // Check if a component definition for this section already exists
    const existingComp = componentDefs.find(comp => comp.name.toLowerCase() === sectionName.toLowerCase());
    if (!existingComp) {
      componentDefs.push({
        name: sectionName.charAt(0).toUpperCase() + sectionName.slice(1), // Capitalize section name
        variant: "default", // Default variant
        contentKey: sectionName, // Link to content
        theme: {}, layout: {}, animation: {}, accessibility: {}, responsiveRules: {}
      });
    }
  });

  return componentDefs;
}

function getLayoutDefinition(layoutBlueprint?: any): LayoutDefinition {
  return layoutBlueprint || {
    type: "split", // Default layout type
    sectionHierarchy: ["hero", "about", "projects", "contact"], // Default hierarchy
  };
}

function getAnimationConfig(animationsBlueprint?: any): AnimationConfig {
  return animationsBlueprint || {
    library: "framer-motion", // Default animation library
    intensity: "subtle", // Default intensity
    pageTransitions: {},
    scrollAnimations: {},
    componentAnimations: {},
    microInteractions: {},
    loadingAnimations: {},
  };
}

function getPlaceholderContent(sections?: any[], contentBlueprint?: any): PlaceholderContent {
  const content: PlaceholderContent = {};

  // Add default content or content based on blueprint
  content.hero = contentBlueprint?.hero || {
    title: "Welcome",
    subtitle: "AI Generated Portfolio",
    description: "Creating a custom portfolio tailored to your needs.",
    cta: "View Projects",
  };

  sections?.forEach(section => {
    if (!content[section.name]) {
      content[section.name] = {
        title: `${section.name.charAt(0).toUpperCase() + section.name.slice(1)} Section`,
        description: `Content for the ${section.name} section.`,
      };
    }
  });

  return content;
}

function getSeoConfig(seoBlueprint?: any): SeoConfig {
  return seoBlueprint || {
    metadata: { title: "AI Portfolio", description: "Generated portfolio website" },
    robots: "index, follow",
    sitemap: "/sitemap.xml",
  };
}

function getAccessibilityConfig(accessibilityBlueprint?: any): AccessibilityConfig {
  return accessibilityBlueprint || {
    rules: {
      semanticHTML: true,
      aria: true,
      keyboardNavigation: true,
      focusManagement: true,
      reducedMotion: false, // Default to false, can be true if specified
      colorContrast: true,
      accessibleForms: true,
    },
  };
}

function getPerformanceConfig(performanceBlueprint?: any): PerformanceConfig {
  return performanceBlueprint || {
    optimizationRules: {
      lazyLoading: true,
      dynamicImports: true,
      imageOptimization: true,
      codeSplitting: true,
      treeShaking: true,
      bundleOptimization: true,
      animationPerformance: true,
    },
  };
}
